### ISSUE TITLE
Are these labs deprecated?

### ISSUE THREAD

**Issue by Sam-Vervaeck** [lowRISC/ibex-demo-system-labs#17]
It seems like this labs repo is not maintained any more? I have been trying to get through the setup op lab 1, but the instructions seem to be faulty at some steps. There are also different tools being used compared to the main ibex repo, e.g. openFPGALoader instead of fusesoc. Where could i get support if i wanted to get this labs working?

**Comment by marnovandermaas** [comment]
There may be some stale instructions in these labs. The best way to get these fixed is opening up an issue with the specific problem that you're having. You can also check the [Ibex demo system](https://github.com/lowRISC/ibex-demo-system) repository to see if any instructions have updated there.

openFPGALoader is used to program bitstreams onto FPGA. FuseSoC is a build environment that can be used to build simulators and bitstreams. Both are still used in the Ibex demo system.
